# This is a basic workflow to help you get started with Actions

name: activity2

# Controls when the action will run. 
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run:
          echo "Hello $NAME, in <years> years, you will be <age>! Won't you feel old?...."
        env:
          NAME: ${{secrets.NAME}}
          AGE: ${{secrets.AGE}}
