name: Activity 2 Workflow
on: push

jobs:
  build:
    name: Start my action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions/activity2
        with:
          NAME: $NAME
          AGE: $AGE
          YEARS: 85
  env:
    NAME: ${{secrets.NAME}}
    AGE: ${{secrets.AGE}}