# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run:
          echo "Hello $NAME, in <years> years, you will be <age>! Won't you feel old?...."
        env:
          NAME: ${{secrets.NAME}}
          AGE: ${{secrets.AGE}}
